[WARNING][2025-05-13 17:20:59,503][log.py:248]Not Found: /
[WARNING][2025-05-13 17:20:59,624][log.py:248]Not Found: /favicon.ico
[WARNING][2025-05-14 09:46:32,307][log.py:248]Unauthorized: /api/system/getInfo
[WARNING][2025-05-14 09:46:32,405][log.py:248]Unauthorized: /api/system/logout
[WARNING][2025-05-14 09:46:40,412][backend.py:91]Caught LDAPError looking up user: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': []})
[WARNING][2025-05-14 19:24:30,067][operation.py:133]"GET - DutController[get_dut] /api/project/getDutOne" (500, '未找到相应的数据')
[ERROR][2025-05-14 19:24:30,076][log.py:248]Internal Server Error: /api/project/getDutOne
[WARNING][2025-05-14 19:24:57,399][operation.py:133]"GET - DutController[get_dut] /api/project/getDutOne" (500, '未找到相应的数据')
[ERROR][2025-05-14 19:24:57,408][log.py:248]Internal Server Error: /api/project/getDutOne
[WARNING][2025-05-15 09:45:13,826][log.py:248]Unauthorized: /api/system/getInfo
[WARNING][2025-05-15 09:45:13,861][log.py:248]Unauthorized: /api/system/logout
[WARNING][2025-05-15 09:45:22,540][backend.py:91]Caught LDAPError looking up user: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': []})
